name: Fedora build CI

on:
  push:
    branches: [ main moz/* ]
  pull_request:
    branches: [ main moz/* ]
  workflow_dispatch:
    branches: [ main moz/* ]

jobs:

  build:

    runs-on: fedora-rawhide

    container:
      image: fedora-rawhide

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: yum install autoconf autoconf-archive automake curl-devel erlang-asn1 erlang-erts erlang-eunit gcc-c++ erlang-os_mon erlang-xmerl erlang-erl_interface help2man libicu-devel libtool perl-Test-Harness
    - name: install w/gui
      run: sudo yum install erlang-reltool
    - name: Compile
      run: make release
    - name: Run tests
      run: make check
