name: MSLegacy

on: [workflow_dispatch,push]

env:
  SOLUTION_FILE_PATH: .
  WXWIDGETS_VERSION: 3.1.4
  BUILD_CONFIGURATION: Release  
  ADD_PATH: "C:\\mozilla-build\\bin;C:\\mozilla-build\\msys\\bin;C:\\mozilla-build\\msys\\local\\bin;C:\\vcpkg\\installed\\x64-windows\\bin;"
  AUTOCONF: "C:\\mozilla-build\\msys\\local\\bin\\autoconf-2.13"
  NATIVE_WIN32_PYTHON: "C:\\mozilla-build\\python\\python2.7.exe"
  LIB: "C:\\vcpkg\\installed\\x64-windows\\lib;C:\\vcpkg\\installed\\x64-windows\\bin"
  INCLUDE: "C:\\vcpkg\\installed\\x64-windows\\include"
  LIBPATH: "C:\\vcpkg\\installed\\x64-windows\\lib"
  LDFLAGS: "/LIBPATH:C:\\vcpkg\\installed\\x64-windows\\lib /LIBPATH:C:\\vcpkg\\installed\\x64-windows\\bin icuin.lib icudt.lib icuuc.lib"
  PKG_CONFIG_PATH: "C:\\vcpkg\\installed\\x64-windows\\lib\\pkgconfig"
  M4: m4
  AWK: awk
  
jobs:
  
  erlang:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          
      - name: Install WSL dependencies
        run: apt update && apt install -y g++-mingw-w64 gcc-mingw-w64 make autoconf unzip

      - name: Elixir
        run: |
          mkdir /mnt/c/Program\ Files/erl9.3.3.14/
          cd /mnt/c/Program\ Files/erl9.3.3.14/
          wget -q https://github.com/elixir-lang/elixir/releases/download/v1.9.4/Precompiled.zip
          unzip -q Precompiled.zip
          rm Precompiled.zip
        
      - name: Install openssl
        shell: cmd
        run: |
          choco install openssl
          move "c:\\Program Files\\OpenSSL-Win64" "c:\\OpenSSL-Win64"
          
      - name: Cache wxWidgets
        uses: actions/cache@v2
        with:
          path: wxWidgets
          key: wxWidgets-${{ env.WXWIDGETS_VERSION }}-${{ runner.os }}

      # actions/cache on Windows sometimes does not set cache-hit even though there was one. Setting it manually.
      - name: Set wxWidgets cache
        id: wxwidgets-cache
        run: |
          if [ -d wxWidgets ]; then
            echo "::set-output name=cache-hit::true"
          else
            echo "::set-output name=cache-hit::false"
          fi
      - name: Download wxWidgets
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WXWIDGETS_VERSION }}/wxWidgets-${{ env.WXWIDGETS_VERSION }}.zip
          unzip wxWidgets-${{ env.WXWIDGETS_VERSION }}.zip -d wxWidgets
          sed -i -r -e 's/wxUSE_POSTSCRIPT +0/wxUSE_POSTSCRIPT 1/' wxWidgets/include/wx/msw/setup.h
          sed -i -r -e 's/wxUSE_WEBVIEW_EDGE +0/wxUSE_WEBVIEW_EDGE 1/' wxWidgets/include/wx/msw/setup.h
      - name: Install WebView2
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd wxWidgets\\3rdparty
          nuget install Microsoft.Web.WebView2 -Version 1.0.705.50 -Source https://api.nuget.org/v3/index.json
          rename Microsoft.Web.WebView2.1.0.705.50 webview2
      - name: Build wxWidgets
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd wxWidgets\\build\\msw
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\Auxiliary\\Build\\vcvars64.bat"
          nmake TARGET_CPU=amd64 BUILD=release SHARED=0 DIR_SUFFIX_CPU= -f makefile.vc
# windows git.exe broken on '*' in filenames          
#      - name: Checkout erlang
#        uses: actions/checkout@v2
#        with:
#          repository: erlang/otp
#          path: otp          
          
      - name: Download source archive
        run: |
          git clone https://github.com/erlang/otp
          cd otp
          git checkout maint-24
          
      - name: Compile Erlang
        run: |
          mkdir -p /mnt/c/opt/local64/pgm/
          cp -R wxWidgets /mnt/c/opt/local64/pgm/wxWidgets-${{ env.WXWIDGETS_VERSION }}
          # tar -xzf ./otp_src.tar.gz
          cd otp
          export ERL_TOP=`pwd`
          export MAKEFLAGS=-j4
          export ERLC_USE_SERVER=true
          eval `./otp_build env_win32 x64`
          ./otp_build configure
          if cat erts/CONF_INFO || cat lib/*/CONF_INFO || cat lib/*/SKIP || cat lib/SKIP-APPLICATIONS; then exit 1; fi
          ./otp_build boot -a
          ./otp_build release -a
          cp /mnt/c/opt/local64/pgm/wxWidgets-${{ env.WXWIDGETS_VERSION }}/3rdparty/webview2/runtimes/win-x64/native/WebView2Loader.dll $ERL_TOP/release/win32/erts-*/bin/
          ./otp_build installer_win32
          ./release/win32/otp_win64_*.exe /S
          cp ./release/win32/otp_win64_*.exe ..
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            otp_win64_*.exe          
  
  mozjs:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: dump env
      shell: python
      continue-on-error: true
      run: |
        import os
        env = os.environ.copy()
        env['PATH'] = 'C:\\mozilla-build\\msys\\bin;C:\\mozilla-build\\msys\\local\\bin;'+env['PATH']
        print(env)        

    - name: Install deps on windows
      shell: powershell
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null

    - name: moz checkout
      uses: actions/checkout@v2
      with:
        repository: mozilla/gecko-dev
        ref: esr78
        path: gecko-dev

    - name: choco install
      run: choco install pkgconfiglite
      
    - name: Install vcpkg dependencies
      shell: pwsh
      run: |
        Install-Module VSSetup -Scope CurrentUser -Force
        vcpkg.exe install icu
        vcpkg.exe integrate install
        
    - name: find things
      shell: bash
      continue-on-error: true
      run: |
        find /c/vcpkg -name icu\*.dll -print
        find /c/vcpkg -name \*.pc -exec cat {} \; -print
        find /c/mozilla-build -type f -name \*make\* -print
        ls -l /c/mozilla-build/msys/local/bin/autoconf-2.13
        echo lld
        find /c/PROGRA~1/LLVM/bin/ -name \*lld\* -print
      
    - name: autoconf mozjs
      shell: python
      working-directory: gecko-dev\js\src
      continue-on-error: true
      run: |
        import subprocess
        import os
        env = os.environ.copy()
        env['PATH'] = 'C:\\mozilla-build\\msys\\bin;C:\\mozilla-build\\msys\\local\\bin;'+env['PATH']
        print(env['PATH'])        
        subprocess.run(["autoconf-2.13"], env=env)
        
    - name: builddir for mozjs
      working-directory: gecko-dev\js\src
      run: mkdir build_OPT.OBJ

    - name: conf mozjs
      working-directory: gecko-dev\js\src\build_OPT.OBJ
      shell: python
      env:
        SRCDIR: ${{ github.workspace}}\gecko-dev\js\src
        OLD_CONFIGURE: ${{ github.workspace }}\gecko-dev\js\src\old-configure
        TOPSRCDIR: ${{ github.workspace }}\gecko-dev
      run: |
        import subprocess
        import os
        env = os.environ.copy()
        env['PATH'] = env['ADD_PATH']+env['PATH']
        subprocess.run(["python.EXE", "../../../configure.py", "--enable-project=js", "--disable-ctypes", "--disable-jit", "--disable-jemalloc", "--enable-optimize", "--enable-hardening", "--with-intl-api", "--build-backends=RecursiveMake", "--with-visual-studio-version=2017", "--with-system-icu", "--disable-debug", "--enable-gczeal", "--target=x86_64-pc-mingw32", "--host=x86_64-pc-mingw32", "--prefix=/c/vcpkg/installed/x64-windows"], env=env)

    - name: make
      working-directory: gecko-dev\js\src\build_OPT.OBJ
      shell: powershell
      run: |
        $env:Path = $env:ADD_PATH + $env:Path
        C:\mozilla-build\bin\mozmake.exe
        C:\mozilla-build\bin\mozmake.exe install
        tar -cvjf ..\..\..\..\vcpkgmozjs.tar.xz C:\vcpkg
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            vcpkgmozjs.tar.xz

