name: MSLegacy

on: [workflow_dispatch]

env:
  MOZTOOLS_PATH: C:\mozilla-build\msys\bin;C:\mozilla-build\bin
  LIBCLANG_PATH: C:\Program Files\LLVM\lib
  AUTOCONF: C:\mozilla-build\msys\local\bin\autoconf-2.13
  NATIVE_WIN32_PYTHON: C:\mozilla-build\python\python2.7.exe
  LIB: C:\relax\vcpkg\installed\x64-windows\lib
  INCLUDE: C:\relax\vcpkg\installed\x64-windows\include
  LIBPATH: C:\relax\vcpkg\installed\x64-windows\lib
  VCPKG_BIN: C:\relax\vcpkg\installed\x64-windows\bin
  M4: m4
  AWK: awk
  
jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Install deps on windows
      shell: powershell
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null

    - name: moz checkout
      uses: actions/checkout@v2
      with:
        repository: mozilla/gecko-dev
        ref: esr78
        path: gecko-dev
        
    - name: ICU checkout
      uses: actions/checkout@v2
      with:
        repository: unicode-org/icu
        path: icubuild
        
    - name: autoconf mozjs
      shell: python
      working-directory: gecko-dev\js\src
      continue-on-error: true
      run: subprocess.run(["C:\mozilla-build\msys\local\bin\autoconf-2.13"])
      
    - name: builddir for mozjs
      working-directory: gecko-dev\js\src
      run: mkdir build_OPT.OBJ

    - name: conf mozjs
      shell: bash
      run: |
        cd gecko-dev/js/src/build_OPT.OBJ
        /c/mozilla-build/msys/bin/sh ../configure --disable-ctypes --disable-jit --disable-jemalloc --enable-optimize --enable-hardening --with-intl-api --build-backends=RecursiveMake --with-visual-studio-version=2017 --with-system-icu --disable-debug --enable-gczeal --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 --prefix=/c/relax/vcpkg/installed/x64-windows
