name: Ubuntu build CI

on:
  push:
    branches: [ main moz/* ]
  pull_request:
    branches: [ main moz/* ]
  workflow_dispatch:
    branches: [ main moz/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get update
    - name: build spidermonkey
      run: |
        wget -q https://download.cdn.mozilla.net/pub/firefox/releases/78.15.0esr/source/firefox-78.15.0esr.source.tar.xz        
        tar xf firefox-78.15.0esr.source.tar.xz
        cd firefox-78.15.0
        ls -l
        cd js/src
        export PYTHON=python3
        export M4=m4
        export AWK=awk
        export AC_MACRODIR=$PWD/build/autoconf/
        autoconf
        mkdir build_OPT.OBJ
        cd build_OPT.OBJ
        ../configure --disable-ctypes --disable-ion --disable-jemalloc --enable-optimize --enable-hardening --with-intl-api --build-backends=RecursiveMake --with-system-icu --disable-debug --enable-gczeal
        make
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-clients_6.3.22-1_amd64.deb
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-server_6.3.22-1_amd64.deb 
    - name: install
      run: sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libmozjs-68-dev libcurl4-openssl-dev elixir ./foundationdb-clients_6.3.22-1_amd64.deb ./foundationdb-server_6.3.22-1_amd64.deb 
    - name: configure
      run: ./configure --spidermonkey-version=68 --disable-docs
    - name: Compile
      run: make release
    - name: Run tests
      run: make check
