name: Ubuntu build CI

on:
  push:
    branches: [ main moz/* ]
  pull_request:
    branches: [ main moz/* ]
  workflow_dispatch:
    branches: [ main moz/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: install
      run: sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libmozjs-78-dev libcurl4-openssl-dev elixir
    - name: configure
      run: ./configure --spidermonkey-version=78 --disable-docs
    - name: Compile
      run: make release
    - name: Run tests
      run: make check
