name: Ubuntu build CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get update
    - name: install
      run: sudo apt-get --no-install-recommends -y install autoconf2.13 build-essential pkg-config libcurl4-openssl-dev erlang-dev rebar elixir
    - name: couch checkout
      uses: actions/checkout@v2
      with:
        path: couch
    - name: look around
      run: ls -l
      
    - name: rebar3 checkout
      uses: actions/checkout@v2
      with:
        repository: erlang/rebar3
        path: rebar3
        
    - name: setup rebar3 
      run: |
        cd rebar3
        ./bootstrap

    - name: ICU checkout
      uses: actions/checkout@v2
      with:
        repository: unicode-org/icu
        path: icubuild
        
    - name: ICU4C with gcc     
      env: 
        PREFIX: ${{github.workspace}}/icu
      run: |
        cd icubuild
        mkdir build;
        cd build;
        ../icu4c/source/runConfigureICU --enable-debug --disable-release Linux/gcc --prefix=$PREFIX --enable-tracing;
        make -j2;
        make -j2 check;
        ( cd ../icu4c/source/test/depstest && ./depstest.py ../../../../build/ );
        make install;
        PATH=$PREFIX/bin:$PATH make -C test/hdrtst check
        ls -l $PREFIX/lib


    - name: build spidermonkey
      run: |
        wget -q https://download.cdn.mozilla.net/pub/firefox/releases/91.3.0esr/source/firefox-91.3.0esr.source.tar.xz        
        tar xf firefox-91.3.0esr.source.tar.xz
        export PKG_CONFIG_PATH=${{github.workspace}}/icu/lib/pkgconfig:$PKG_CONFIG_PATH
        export AC_MACRODIR=${{github.workspace}}/firefox-91.3.0/build/autoconf/
        cd firefox-91.3.0
        ls -l  
        export PYTHON=python3
        export M4=m4
        export AWK=awk
        cd js/src
        sh ../../build/autoconf/autoconf.sh --localdir=$PWD configure.in > configure
        chmod +x configure
        mkdir ${{github.workspace}}/build_OPT.OBJ
        cd ${{github.workspace}}/build_OPT.OBJ
        ${{github.workspace}}/firefox-91.3.0/js/src/configure --prefix=${{github.workspace}}/moz-js --disable-ctypes --disable-jit --disable-jemalloc --enable-optimize --enable-hardening --with-intl-api --build-backends=RecursiveMake --with-system-icu --disable-debug --enable-gczeal
        make
        make install
        ls -l ${{github.workspace}}/moz-js
        
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-clients_6.3.22-1_amd64.deb
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-server_6.3.22-1_amd64.deb 
    - name: install
      run: sudo apt-get --no-install-recommends -y install ./foundationdb-clients_6.3.22-1_amd64.deb ./foundationdb-server_6.3.22-1_amd64.deb
    - name: configure
      run: |
        cd couch
        sh ./configure --spidermonkey-version=91 --disable-docs
    - name: Compile
      run: |
        cd couch
        make release
    - name: Run tests
      run: |
        cd couch
        make check
