name: Ubuntu build CI

on:
  push:
    branches: [ main moz/* ]
  pull_request:
    branches: [ main moz/* ]
  workflow_dispatch:
    branches: [ main moz/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-clients_6.3.22-1_amd64.deb
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-server_6.3.22-1_amd64.deb 
    - name: install
      run: sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libmozjs-68-dev libcurl4-openssl-dev elixir ./foundationdb-clients_6.3.22-1_amd64.deb ./foundationdb-server_6.3.22-1_amd64.deb 
    - name: configure
      run: ./configure --spidermonkey-version=68 --disable-docs
    - name: Compile
      run: make release
    - name: Run tests
      run: make check
