name: Ubuntu build CI

on:
  push:
    branches: [ main moz/* ]
  pull_request:
    branches: [ main moz/* ]
  workflow_dispatch:
    branches: [ main moz/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get update

    - name: ICU checkout
      uses: actions/checkout@v2
      with:
        repository: unicode-org/icu
        path: icubuild
        
    - name: ICU4C with gcc     
      env: 
        PREFIX: ${{github.workspace}}/icu
      run: |
        cd icubuild
        mkdir build;
        cd build;
        ../icu4c/source/runConfigureICU --enable-debug --disable-release Linux/gcc --prefix=$PREFIX --enable-tracing;
        make -j2;
        make -j2 check;
        ( cd ../icu4c/source/test/depstest && ./depstest.py ../../../../build/ );
        make install;
        PATH=$PREFIX/bin:$PATH make -C test/hdrtst check
        ls -l $PREFIX/lib


    - name: build spidermonkey
      run: |
        wget -q https://download.cdn.mozilla.net/pub/firefox/releases/78.15.0esr/source/firefox-78.15.0esr.source.tar.xz        
        tar xf firefox-78.15.0esr.source.tar.xz
        export PKG_CONFIG_PATH=${{github.workspace}}/icu/lib/pkgconfig:$PKG_CONFIG_PATH
        cd firefox-78.15.0
        ls -l  
        export PYTHON=python3
        export M4=m4
        export AWK=awk
        export AC_MACRODIR=$PWD/build/autoconf/
        cd js/src
        mkdir build_OPT.OBJ
        cd build_OPT.OBJ
        ../configure --disable-ctypes --disable-jit --disable-jemalloc --enable-optimize --enable-hardening --with-intl-api --build-backends=RecursiveMake --with-system-icu --disable-debug --enable-gczeal
        make
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-clients_6.3.22-1_amd64.deb
    - name: wget 
      run: wget https://www.foundationdb.org/downloads/6.3.22/ubuntu/installers/foundationdb-server_6.3.22-1_amd64.deb 
    - name: install
      run: sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libmozjs-68-dev libcurl4-openssl-dev elixir ./foundationdb-clients_6.3.22-1_amd64.deb ./foundationdb-server_6.3.22-1_amd64.deb 
    - name: configure
      run: ./configure --spidermonkey-version=68 --disable-docs
    - name: Compile
      run: make release
    - name: Run tests
      run: make check
